photomanager/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from viewer.models import Photo
from viewer.views import IndexView

admin.site.register(Photo)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('viewer/', include('viewer.urls', namespace='viewer')),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

viewer/urls.py
from django.urls import path

from viewer.views import (
    IndexView, PhotoListView, PhotoDetailView, PhotoCreateView,
    PhotoUpdateView, PhotoDeleteView, PhotoTableListView
)

app_name = 'viewer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('photo/list', PhotoListView.as_view(), name='photo_list'),
    path('photo/tablelist', PhotoTableListView.as_view(), name='table_list'),
    path('photo/detail/<pk>', PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/delete', PhotoListView.as_view(), name='photo_confirm_delete'),
    path('photo/update/<pk>', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo/delete/<pk>', PhotoDeleteView.as_view(), name='photo_delete'),
    path('photo/create', PhotoCreateView.as_view(), name='photo_create'),
    ]

viewer/models.py
from django.db.models import CharField, Model, IntegerField, ImageField


class Photo(Model):
    title = CharField(max_length=128)
    albumId = IntegerField()
    # i didnt know , i need to create additional model and connect it with
    # fierign key. But if i havent any album data instead id in jsonholder,
    # I will create standart integer.
    width = IntegerField(blank=True, null=True)
    height = IntegerField(blank=True, null=True)
    color = CharField(max_length=18)
    url = ImageField()
    thumbnailUrl = ImageField()

viewer/forms.py
import re

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django.core.exceptions import ValidationError
from django.forms import CharField, IntegerField, ModelForm, ImageField, URLField

from viewer.models import Photo


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')


class PhotoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('title'),
                Column('albumId')),
            'url',
            Submit('submit', 'Submit')
        )

    class Meta:
        model = Photo
        fields = '__all__'

    title = CharField(validators=[capitalized_validator])
    albumId = IntegerField(min_value=1, max_value=4)
    url = URLField()
    thumbnailUrl = ImageField()

    def clean_url(self):
        initial = self.cleaned_data['url']
        sentences = re.sub(r'\s*\.\s*', '', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)

viewer/views.py
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
)
from django_tables2 import SingleTableView




from django.urls import reverse_lazy

from viewer.models import Photo
from viewer.forms import PhotoForm
from viewer.tables import PhotoTable


class PhotoTableListView(SingleTableView):
    model = Photo
    table_class = PhotoTable
    template_name = 'table_list.html'


class PhotoListView(ListView):
    model = Photo
    template_name = 'photo_list.html'


class PhotoDetailView(DetailView):
    template_name = 'photo_detail.html'
    model = Photo


class PhotoCreateView(CreateView):
    template_name = 'form.html'
    form_class = PhotoForm
    success_url = reverse_lazy('viewer:photo_list')


class PhotoUpdateView(UpdateView):
    template_name = 'form.html'
    model = Photo
    form_class = PhotoForm
    success_url = reverse_lazy('viewer:photo_list')


class PhotoDeleteView(DeleteView):
    template_name = 'photo_confirm_delete.html'
    model = Photo
    success_url = reverse_lazy('viewer:photo_list')


class IndexView(PhotoListView):
    template_name = 'index.html'

viewer/templates/base.html
{% load bootstrap4 %}
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}" {% endif %}>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Manager</title>
    {% block styles %}{% bootstrap_css %}{% endblock %}
    {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="{% url 'index' %}">Photo Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'index' %}">
                    Home
                </a>
                <div class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" href="#"
                       data-toggle="dropdown">
                        Photos
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item"
                           href="{% url 'viewer:photo_list' %}">List</a>
                                                <a class="dropdown-item"
                           href="{% url 'viewer:table_list' %}">Table List</a>
                        <a class="dropdown-item"
                           href="{% url 'viewer:photo_create' %}">Create</a>
                    </div>
                </div>
            </div>
            <div class="navbar-nav ml-auto">
                <div class="nav-item dropdown">
                </div>
            </div>
        </div>
    </div>
</nav>
<div class="container">
    <div class="jumbotron">
        {% block title %}
        {% if title %}<h1>{{ title }}</h1>{% endif %}
        {% endblock %}
        {% block messages %}
        {% for message in messages %}
        {% if message.tags.split.0 == 'error' %}
        <div class="alert alert-danger alert-dismissable fade show">
            <button type="button" class="close" data-dismiss="alert">&times;
            </button>
            {{ message.message }}
        </div>
        {% else %}
        <div class="alert alert-{{ message.tags.split.0 }} alert-dismissable fade show">
            <button type="button" class="close" data-dismiss="alert">&times;
            </button>
            {{ message.message }}
        </div>
        {% endif %}
        {% endfor %}
        {% endblock %}
        {% block content %}{% endblock %}
    </div>
</div>
</body>

</html>

viewer/templates/form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

viewer/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to basic Photo Manager!</h1>
<ul>
    {% for photo in photos %}
    <li>
        {{ photo.title }} - ({{ photo.albumId }})
    </li>
    {% endfor %}
</ul>
{% endblock %}

viewer/templates/photo_confirm_delete.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <form method="post">
    {% csrf_token %} 
    <p>
      Are you sure you want to delete photo "{{ object.title }}" from manager?
    </p> 
    <input type="submit" value="Submit" class="btn btn-danger">
  </form> 
{% endblock %}

viewer/templates/photo_detail.html
{% extends "base.html" %}

{% load static %}
{% load photo_extras %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'photo_detail.css' %}" />
{% endblock %}

{% block content %}
<div class="row">
    {% if photo.url %}
      <div class="col-4">
        <img src="{{ photo.url }}" class="max-300x450"/>
      </div>
    {% endif %}
    <div class="col">
      {{ photo|attr_as_p:'id' }}
      {{ photo|attr_as_p:'title' }}
      {{ photo|attr_as_p:'color' }}
      {{ photo|attr_as_p:'albumId' }}
    </div>
  </div>
{% endblock %}

viewer/templates/photo_list.html
{% extends "base.html" %}

{% load static %}
{% load render_table from django_tables2 %}
{% load photo_extras %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'photo_list.js' %}"></script>
{% endblock %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'photo_list.css' %}" />
{% endblock %}

{% block content %}
  <ul>
    {% for photo in object_list %}
     <li>
        {% if photo.url %}
          <span class="cursor-default show-image" data-img="{{ photo.url }}">
            {% photo_format photo short=True %}
          </span>
        {% else %}
          <span class="cursor-default">
            {% photo_format photo short=True %}
          </span>
        {% endif %}
        <a href="{% url 'viewer:photo_detail' photo.pk %}">detail</a> /
        <a href="{% url 'viewer:photo_update' photo.pk %}">update</a> /
        <a href="{% url 'viewer:photo_delete' photo.pk %}">delete</a>
      </li>
    {% endfor %}
  </ul>

<nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}

viewer/templates/table_list.html
{% extends "base.html" %}

{% load static %}
{% load render_table from django_tables2 %}
{% load photo_extras %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'photo_list.js' %}"></script>
{% endblock %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'photo_list.css' %}" />
{% endblock %}

{% block content %}
        {% render_table table %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}